package xyz.asitanokibou.common.security;

import jdk.nashorn.internal.ir.annotations.Ignore;
import org.apache.commons.codec.binary.Base64;
import org.junit.jupiter.api.Test;

import java.security.NoSuchAlgorithmException;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.InvalidKeySpecException;
import java.util.Map;

public class RSATest {

    //RSA-OAEP: RSAES OAEP using default parameters
    String rsa_oaep_privateKey = "-----BEGIN PRIVATE KEY-----\n" +
            "MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAILdM0yPUzezDvP4\n" +
            "k+ytd7eNQzNCZ1HcDdpfI5n7UTucujiPkBGIFFhJ7IIwr3EkdtiPfZVJO3Q84EZ3\n" +
            "cMciZHd7oLrnrQlvTbripMp1aQ5VSBBA/+DL63PrwmesXTWCXcYt8t4cB+wj54QW\n" +
            "FCo+4gVTJ4DrUaPcO/wq7sxflGORAgMBAAECgYAOFFRvmT//zyD9uLHZlfQ6aFVh\n" +
            "j3RkR0OqSfAfof1kZ4FVkoSSjkx6D0IF480MZDrxI8cEJ8PgxqfujO0yT431cXaT\n" +
            "jeEqzkSvr1mcm49+FtbdfY92EHM71Q8Y66unvgCPZZ0m7g9wC/LK8oEaUGKGHFf8\n" +
            "zNIHOGw3XR3te2cZwQJBAMUPIAeX8uMYhVrD18pIHsfYkFcDc2LBC+9MuuYxgghO\n" +
            "60Lda67v4DeY4copKgHZUU5KItT0894p1sisWHqE1rkCQQCqAYCSk8Y4kz7lii0L\n" +
            "MW6KwCAVqj3/SK0IAgB4Tst885xIVhb/Zb1N+oPAbM4CHSBBNAbimDq0bLQFhWrO\n" +
            "WQeZAkBd8hQHCr3U3n/VAcECwtdJ10kY8qAz2GzkLOR9keS4KUennQAVam6uksgy\n" +
            "JOXN89j7RgTNGeqZY8Dt8pxL7MChAkBoVcWvr4uemxelzhh43xyFgQXv5exoqRSw\n" +
            "bnIVY95U0Dmg110D30+/9Lg5N01zVKa//YsgM+cLZg9RuCDlhRQ5AkAOfy8sNdPu\n" +
            "ji8w8sNrj36hnEntcVa24tXdi1NH8q3YtjTAQZtVMy8B79a0EO+Usy2Dk8vaeTLH\n" +
            "BNobEqhkFSCA\n" +
            "-----END PRIVATE KEY-----";//generated by mkjwk.org

    //RSA-OAEP: RSAES OAEP using default parameters
    String rsa_oaep_publicKey = "-----BEGIN PUBLIC KEY-----\n" +
            "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCC3TNMj1M3sw7z+JPsrXe3jUMz\n" +
            "QmdR3A3aXyOZ+1E7nLo4j5ARiBRYSeyCMK9xJHbYj32VSTt0POBGd3DHImR3e6C6\n" +
            "560Jb0264qTKdWkOVUgQQP/gy+tz68JnrF01gl3GLfLeHAfsI+eEFhQqPuIFUyeA\n" +
            "61Gj3Dv8Ku7MX5RjkQIDAQAB\n" +
            "-----END PUBLIC KEY-----";//generated by mkjwk.org

    @Test
    public void testEncrypt() throws InvalidKeySpecException, NoSuchAlgorithmException {
        String encodedData = RSAUtils.privateEncrypt("123456", rsa_oaep_privateKey);
        System.out.println(encodedData);

        String decrypt = RSAUtils.publicDecrypt(encodedData, rsa_oaep_publicKey);
        System.out.println(decrypt);
    }

    @Test
    @Ignore
    public void testCreateKeyPair(){
        Map<String, String> keys = RSAUtils.createKeys(1024);

        String publicKey = keys.get(RSAUtils.PUBLIC_KEY_NAME);
        String privateKey = keys.get(RSAUtils.PRIVATE_KEY_NAME);

        System.out.println("---privateKey---");
        System.out.println(privateKey);
        System.out.println();

        System.out.println("---publicKey---");
        System.out.println(publicKey);
    }

    @Test
    public void testGeneratePublicKey() throws InvalidKeySpecException, NoSuchAlgorithmException {

        RSAPrivateKey privateKey = RSAUtils.getPrivateKey(rsa_oaep_privateKey);
        System.out.println(privateKey.getClass());

        RSAPublicKey rsaPublicKey = RSAUtils.generatePublicKeyFromPrivateKey(privateKey);
        System.out.println("PublicKey generated from privateKey : " +  Base64.encodeBase64String(rsaPublicKey.getEncoded()));
    }
}
